### PR TITLE
Update navigation

### PR DESCRIPTION
**Pull request by markknol**
try-haxe

This will update the navigation to the new format.

- removed tabs on left panel (are in view-menu now)
- same bootstrap version as on haxe.org
- small layout updates to fix bootstrap change
- font awesome icons everywhere, because bootstrap does not have icons in it

I also fixed a broken favicon path.

Please double check.

---
Will eventually close
https://github.com/HaxeFoundation/haxe.org/issues/105
https://github.com/HaxeFoundation/Project-Management/issues/34

### CODE REVIEW

**Comment by profelis** [comment]
+1 click for every option, really?

**Comment by clemos** [comment]
Nice one :D 

I agree with @profelis, though, the "View" menu feels worse than the current version.
How about : 
* Keeping the Sources / Options tabs 
* Creating an "Examples" dropdown in the top menu, move the examples there 
* Remove the "File" dropdown, keep only "New"
This way, we would have : 
New | Examples | About 
in the top menu,
and then
Source | Options | Build + Run
in the tabs / buttons section.

"New" and "Examples" can eventually be merged in a single "File" menu if you think it's better.
* New
* separator
* Examples (title)
* Example 1
* Example 2
* ...

Benefits : 
* Tabs and frames will be aligned vertically
* The "Examples" section will make more sense here, out of the "Source" section

What do you think ?

**Comment by anissen** [comment]
If you're working on general layout, I would also love to have the code and output containers expanded to fill the entire height of the page :+1:

**Comment by markknol** [comment]
@clemos sounds like a very good plan.
@anissen will check if that is easy to fix.

**Comment by clemos** [comment]
@anissen @markknol I can do the vertical resizing part.

**Comment by clemos** [comment]
PS: Regarding the "about" section (also true on the current design):
* I've never liked the "Download Haxe" "Learn more" buttons. I think they should be simple links
* There's not enough vertical space between titles and sections
* The Haxe logo feels weird (also: right margin problem on your version)
I think this whole thing should be visually simplified, if possible.

**Comment by clemos** [comment]
@markknol Can you do the changes I proposed, or do you want me to do them ?

**Comment by markknol** [comment]
No I can do them, give me some time. It's on the list.

If you want to do the vertical stretch, wait a bit until I finished this.

**Comment by clemos** [comment]
Yes, sure, I'll wait for your update.
Thanks a lot for your work :)

**Pull request closed without merging**
