### PR TITLE
Update navigation / layout

### PR DESCRIPTION
**Pull request by markknol**
try-haxe-2

- moved examples to top menu
- moved about button to top menu, updated about page a bit
- layout updates 
- font awesome icons everywhere, because bootstrap does not have menu icons in it
- I also fixed a broken favicon path

Please double check.

### CODE REVIEW

**Comment by markknol** [comment]
I found out I messed up some git bits with the previous version, so that's why this is a new version.

I kept the about page as tab, but invisible in the tab menu, otherwise you can never navigate back to the source. The download/readmore buttons are just removed. The Haxe logo is clickable, I think that is already enough.

**Comment by clemos** [comment]
It's great, I'll publish it in the next couple of days.
Thanks :)

**Comment by markknol** [comment]
Thanks!

**Comment by clemos** [comment]
It's online :)
Also, I've added vertical resize, @anissen @markknol 
Let me know how it works for you.

**Comment by clemos** [comment]
Vertical resizing has a weird behaviour on mobile; I ll see what I can do

**Comment by markknol** [comment]
Hey looks good! Thanks

**Comment by anissen** [comment]
That's great, good job! :+1: 
My only nitpick is that you now have to scroll to see the box with compilation times.

**Pull request merged**
