### PR TITLE
Dead Code Elimination option

### PR DESCRIPTION
**Pull request by markknol**
This should give dce full/no as an option, as requested by @Gama11 on the haxe irc-channel.

I haven't test it completely because of #69 but it does get saved an value is stored+used, but in theory it should work :smile: 

A nice first case to test with `dce=no` would be this: http://try.haxe.org/#8DD2c if it works, `imNotDead()` should not be in the output.

### CODE REVIEW

**Comment by clemos** [comment]
It's online (as well as the example) !
Thanks a lot

**Comment by markknol** [comment]
Works !! Good stuff!

**Comment by Simn** [comment]
I had to ctrl F5 try.haxe because I was getting some "Invalid DCE mode: null" or something error. You may want to resolve that to something to avoid annoying browser cache issues.

**Comment by profelis** [comment]
```Build failure
Invalid dce : null```
:(

**Pull request merged**
